### ISSUE TITLE
HuViz User Tests

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#121]
## PART ONE: formal Qualtrics surveys

We finished 19 tests previously. Those tests have been merged into a single .csv and uploaded to Qualtrics. Kim recently finished an additional two tests; and there is another final test planned with an established scholar, bringing the total to 22.

- [ ] Finish final user test with established scholar
- [ ] Download the three most recent tests and merge data with previous 19 tests into final .csv; re-upload to Qualtrics
- [ ] Add point form rough notes from additional tests to the [Testing Highlights Doc](https://docs.google.com/document/d/19mpVXfQr4nNIsQChIoBHLH3G6UHOxc7OmVxH9tMwn30/edit?usp=sharing)
- [ ] Finish the lit. review section of the paper
   -  NOTE: Some of the lit review work has already been done; see [INKE proposal](https://docs.google.com/document/d/1gOZuKlbjEXTISwmhRqRRu5d7s_qXREgkcAu78O3Yh70/edit?usp=sharing) and [rough draft](https://docs.google.com/document/d/1I7BXYaksoLfpYUpcg-evpEkFPPm_PcoNSZLsBE7O2e0/edit?usp=sharing) for resources

## Part TWO: 1-3 shorter, informal tests

We will also experiment with a few shorter, more informal test sessions. At least one of the sessions will be observed live via Skype. Afterwards we'll have a discussion together as a team about our findings/takeaways from the test session and any steps that we'd like to take to address issues/bugs that we discovered; the test subject could also take part in the session if he/she wished.

- [ ] Email possible testers and arrange time for session

### TWO TEST STYLES:

- [ ] Provide users with intro paragraph and ask to explore/play 
- [ ] Invite experienced users (e.g. Jana, Kathryn, Mihela) to experiment with and give feedback on the new OA models
