### ISSUE TITLE
Positive feedback on geonames authentification

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#242]
Nice to have the feedback when geonames user name doesn't work. 

Would be nice to have positive feedback too when it does, because right now nothing happens.

Perhaps a check mark could appear to the left or right of the text box in which the user name has been entered?

### GeoNames docs
https://www.geonames.org/export/credits.html

* Note the complexity of the math.  It isn't as simple as n-hits-per-t.

https://www.geonames.org/export/webservice-exception.html

* 10 unauthorized
* 18 hourly limit reached
* 19 daily limit reached
* 20 weekly limit reached

### SubTasks

* [x] improve instructions
* [x] change color and state of input (bad/red, good/green, empty/grey, trying/orange, untried/orange)
* [x] show help when username broken
* [x] respect the limit again
* [x] clicking user icon should show help
* [ ] cope with limit hits by creating a new state `limited` and new transitions `limit_hr`, `limit_day` and `limit_wk`
* ~~fix keeps-doing-lookups-even-after-all-geonames-are-named bug~~  _obviated by preset_discover_names_remaining_

**Comment by smurp** [comment]
* perhaps a green checkmark when it has been validated in this session
* warning amber alert icon when it is acting strangely (has the account had email validated?)
* error red icon when it is non-existent etc

**Comment by smurp** [comment]
Implemented something like this:
![image](https://user-images.githubusercontent.com/774119/55967152-16cfe680-5c7a-11e9-922a-4fef2ca9ca97.png)

http://alpha.huviz.dev.nooron.com/#load+/data/geoname_username_widget_states.ttl+with+/data/owl_mini.ttl

* set "boxed labels"
* set "show adjacent edge labels"
* `Label and Activate All`
* turn down the charge and gravity settings to taste

**Comment by antimony27** [comment]
Work has surpassed this. Closing as its a distraction to current work.
